### ISSUE TITLE
Multiple warnings  at Pod install

### ISSUE THREAD

**Issue by adongarwar** [aharren/LibComponentLogging-Core#27]
I'm running pod install with following specs. Installing stage is fine, but later i see following warnings at the end. Also, running lcl_configure pod says "command not found. The name of the file that actually exists is  pod. lcl_configure. Please help. Thanks in advance-

platform :ios, '8.0'
pod 'LibComponentLogging-Core'
pod 'LibComponentLogging-LogFile'
pod 'LibComponentLogging-qlog'

[!] Found multiple specifications for `LibComponentLogging-Core (1.3.3)`:
- /Users/adongarwar/.cocoapods/repos/lcl/Specs/LibComponentLogging-Core/1.3.3/LibComponentLogging-Core.podspec.json
- /Users/adongarwar/.cocoapods/repos/master/Specs/LibComponentLogging-Core/1.3.3/LibComponentLogging-Core.podspec.json

[!] Found multiple specifications for `LibComponentLogging-Core (1.3.2)`:
- /Users/adongarwar/.cocoapods/repos/lcl/Specs/LibComponentLogging-Core/1.3.2/LibComponentLogging-Core.podspec.json
- /Users/adongarwar/.cocoapods/repos/master/Specs/LibComponentLogging-Core/1.3.2/LibComponentLogging-Core.podspec.json

[!] Found multiple specifications for `LibComponentLogging-Core (1.3.1)`:
- /Users/adongarwar/.cocoapods/repos/lcl/Specs/LibComponentLogging-Core/1.3.1/LibComponentLogging-Core.podspec.json
- /Users/adongarwar/.cocoapods/repos/master/Specs/LibComponentLogging-Core/1.3.1/LibComponentLogging-Core.podspec.json

[!] Found multiple specifications for `LibComponentLogging-Core (1.2.2)`:
- /Users/adongarwar/.cocoapods/repos/lcl/Specs/LibComponentLogging-Core/1.2.2/LibComponentLogging-Core.podspec.json
- /Users/adongarwar/.cocoapods/repos/master/Specs/LibComponentLogging-Core/1.2.2/LibComponentLogging-Core.podspec.json

[!] Found multiple specifications for `LibComponentLogging-Core (1.2.1)`:
- /Users/adongarwar/.cocoapods/repos/lcl/Specs/LibComponentLogging-Core/1.2.1/LibComponentLogging-Core.podspec.json
- /Users/adongarwar/.cocoapods/repos/master/Specs/LibComponentLogging-Core/1.2.1/LibComponentLogging-Core.podspec.json

[!] Found multiple specifications for `LibComponentLogging-Core (1.1.6)`:
- /Users/adongarwar/.cocoapods/repos/lcl/Specs/LibComponentLogging-Core/1.1.6/LibComponentLogging-Core.podspec.json
- /Users/adongarwar/.cocoapods/repos/master/Specs/LibComponentLogging-Core/1.1.6/LibComponentLogging-Core.podspec.json

[!] Found multiple specifications for `LibComponentLogging-Core (1.1.5)`:
- /Users/adongarwar/.cocoapods/repos/lcl/Specs/LibComponentLogging-Core/1.1.5/LibComponentLogging-Core.podspec.json
- /Users/adongarwar/.cocoapods/repos/master/Specs/LibComponentLogging-Core/1.1.5/LibComponentLogging-Core.podspec.json

[!] Found multiple specifications for `LibComponentLogging-Core (1.1.4)`:
- /Users/adongarwar/.cocoapods/repos/lcl/Specs/LibComponentLogging-Core/1.1.4/LibComponentLogging-Core.podspec.json
- /Users/adongarwar/.cocoapods/repos/master/Specs/LibComponentLogging-Core/1.1.4/LibComponentLogging-Core.podspec.json

[!] Found multiple specifications for `LibComponentLogging-LogFile (1.2.2)`:
- /Users/adongarwar/.cocoapods/repos/lcl/Specs/LibComponentLogging-LogFile/1.2.2/LibComponentLogging-LogFile.podspec.json
- /Users/adongarwar/.cocoapods/repos/master/Specs/LibComponentLogging-LogFile/1.2.2/LibComponentLogging-LogFile.podspec.json

[!] Found multiple specifications for `LibComponentLogging-LogFile (1.2.1)`:
- /Users/adongarwar/.cocoapods/repos/lcl/Specs/LibComponentLogging-LogFile/1.2.1/LibComponentLogging-LogFile.podspec.json
- /Users/adongarwar/.cocoapods/repos/master/Specs/LibComponentLogging-LogFile/1.2.1/LibComponentLogging-LogFile.podspec.json

[!] Found multiple specifications for `LibComponentLogging-LogFile (1.1.5)`:
- /Users/adongarwar/.cocoapods/repos/lcl/Specs/LibComponentLogging-LogFile/1.1.5/LibComponentLogging-LogFile.podspec.json
- /Users/adongarwar/.cocoapods/repos/master/Specs/LibComponentLogging-LogFile/1.1.5/LibComponentLogging-LogFile.podspec.json

[!] Found multiple specifications for `LibComponentLogging-qlog (1.1.1)`:
- /Users/adongarwar/.cocoapods/repos/lcl/Specs/LibComponentLogging-qlog/1.1.1/LibComponentLogging-qlog.podspec.json
- /Users/adongarwar/.cocoapods/repos/master/Specs/LibComponentLogging-qlog/1.1.1/LibComponentLogging-qlog.podspec.json

[!] Found multiple specifications for `LibComponentLogging-qlog (1.0.3)`:
- /Users/adongarwar/.cocoapods/repos/lcl/Specs/LibComponentLogging-qlog/1.0.3/LibComponentLogging-qlog.podspec.json
- /Users/adongarwar/.cocoapods/repos/master/Specs/LibComponentLogging-qlog/1.0.3/LibComponentLogging-qlog.podspec.json

[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Carebook` to `../Pods/Target Support Files/Pods/Pods.debug.xcconfig` or include the `../Pods/Target Support Files/Pods/Pods.debug.xcconfig` in your build configuration.

[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Carebook` to `../Pods/Target Support Files/Pods/Pods.distribution-adhoc.xcconfig` or include the `../Pods/Target Support Files/Pods/Pods.distribution-adhoc.xcconfig` in your build configuration.

**Comment by aharren** [comment]
Can you remove the `/Users/adongarwar/.cocoapods/repos/lcl/`folder? The CocoaPods master repository at `/Users/adongarwar/.cocoapods/repos/master/`already contains the latest specs.

**Comment by aharren** [comment]
For `lcl_configure`, please add the `LibComponentLogging-pods` pod:

```
platform :ios, 8

pod 'LibComponentLogging-Core'
pod 'LibComponentLogging-LogFile'
pod 'LibComponentLogging-qlog'

pod 'LibComponentLogging-pods'
```

After `pod install` you can then simply run `Pods/LibComponentLogging-pods/configure/lcl_configure pod`

**Comment by adongarwar** [comment]
Removed /Users/adongarwar/.cocoapods/repos/lcl/, and getting semantic issues. 
![screen shot 2015-03-30 at 1 56 55 pm](https://cloud.githubusercontent.com/assets/4019449/6906581/a6a1a4a8-d6e4-11e4-842f-fd70c0b31c37.png)

**Comment by aharren** [comment]
Can you check that your lcl_config_components.h file contains these items?

**Comment by adongarwar** [comment]
There is no file like lcl_config_components.h in my project. Only following 2 files.
Update : Got it. There was 3 files on the root of project, imported 3 of them (components, extensions, logger). Still the semantic issues r still there.
![screen shot 2015-03-30 at 2 08 36 pm](https://cloud.githubusercontent.com/assets/4019449/6906869/4a2efff2-d6e6-11e4-9a16-f17042591ddc.png)

**Comment by adongarwar** [comment]
Got it. There was 3 files on the root of project,  imported 3 of them (components, extensions, logger). Still the semantic issues r still there.

**Comment by adongarwar** [comment]
this is hw components file looks like -

/_::lcl_configure:begin::_/
/_::lcl_configure:end::_/

**Comment by aharren** [comment]
You need to add a line in the components file which defines your Carebook component

**Comment by aharren** [comment]
Something like

_lcl_component(Carebook,            "carebook",             "Carebook")

**Comment by adongarwar** [comment]
Got it. Thanks. It's compiling now.
