### ISSUE TITLE
Using %s directive in CFString warning in XCode 6.3

### ISSUE THREAD

**Issue by 4PixelsDev** [aharren/LibComponentLogging-Core#29]
After update to XCode 6.3 the following warning has shown:
"Using %s directive in CFString which is being passed as a formatting argument to the formatting CFfunction"

The warning point to  `#   define _lcl_logger(_component, _level, _format, ...)` in lcl.h file

**Comment by 4PixelsDev** [comment]
The issue is reproducible in "LibComponentLogging-LogFile-Example project".

**Comment by aharren** [comment]
Do you use the NSLog-based logger? It looks like the %s warnings originate from the added fields for component, level, file, function.
