### ISSUE TITLE
fatal: Not a git repository: Pods/LibComponentLogging-pods/configure/../.git/modules/configure

### ISSUE THREAD

**Issue by adongarwar** [aharren/LibComponentLogging-Core#30]
I'm trying to push a project to git. It fails with the error mentioned in title. Terminal logs are as follows.

adongarwar:ios adongarwar$ git init
Initialized empty Git repository in /Users/adongarwar/CIS-Git/ios/.git/
adongarwar:ios adongarwar$ git add ios
fatal: pathspec 'ios' did not match any files
adongarwar:ios adongarwar$ cd ..
adongarwar:CIS-Git adongarwar$ git add ios
fatal: Not a git repository (or any of the parent directories): .git
adongarwar:CIS-Git adongarwar$ cd ios
adongarwar:ios adongarwar$ git add .
fatal: Not a git repository: Pods/LibComponentLogging-pods/configure/../.git/modules/configure
Important point - My Project is in SVN already. I manually copy the project folder to a new folder and then try initialing git.

Thanks in advance.

**Comment by aharren** [comment]
Please remove the `.git` folder in `Pods/LibComponentLogging-pods/configure/` (`Pods/LibComponentLogging-pods/configure/.git`). This should do the trick.

**Comment by aharren** [comment]
https://github.com/CocoaPods/CocoaPods/issues/3997

**Comment by aharren** [comment]
fixes: https://github.com/CocoaPods/Specs/pull/13385

**Comment by aharren** [comment]
Updated pod specs are merged into CocoaPods/Specs master.

You can update your pods in your project, it should remove the unwanted `.git` folder.

**Comment by adongarwar** [comment]
Removing the .git folder worked. Thanks for your help.
